CREATE TABLE `salida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analisis_id` INT NULL,
  `entrada_id` INT NULL,
  `mercaderia_id` INT NULL,
  `parte_proceso_id` INT NULL,
  `img_dir` VARCHAR(300) NULL,
  `cp_numero` VARCHAR(16) NULL,
  `ctg` VARCHAR(16) NULL,
  `fecha_carga` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `titular_CP_id` INT NULL,
  `remitente_comercial_id` INT NULL,
  `representante_entregador` VARCHAR(64) NULL,
  `destinatario_id` INT NULL,
  `grano_especie` INT NULL,
  `calidad` VARCHAR(64) NULL,
  `peso_bruto` INT NULL,
  `peso_tara` INT NULL,
  `obsercaciones` VARCHAR(512) NULL,
  `destino` INT NULL,
  `transporte` INT NULL,
  `patente_camion` VARCHAR(32) NULL,
  `patente_acoplado` VARCHAR(32) NULL,
  `KM_a_recorrer` INT NULL,
  PRIMARY KEY (`id`));