CREATE TABLE `entrada` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `analisis_id` int(11) NOT NULL,
  `numero_ingreso` int(11) DEFAULT NULL,
  `carta_de_porte` varchar(16) DEFAULT NULL,
  `cert_de_deposito` varchar(16) DEFAULT NULL,
  `CTG` varchar(16) DEFAULT NULL,
  `peso_bruto` int(11) NOT NULL,
  `peso_tara` int(11) NOT NULL,
  `chofer` varchar(64) DEFAULT NULL,
  `patente_camion` varchar(32) DEFAULT NULL,
  `patente_acoplado` varchar(32) DEFAULT NULL,
  `titular_CP` int(11) DEFAULT NULL,
  `remitente_comercial` int(11) DEFAULT NULL,
  `destinatario` int(11) DEFAULT NULL,
  `transporte` int(11) DEFAULT NULL,
  `procedencia` int(11) DEFAULT NULL,
  `grano_especie_id` int(11) NULL,
  `mercaderia_id` int(11) NULL,
  `cantidad_bolsa` int(11) DEFAULT NULL,
  `tipo_bolsa` int(11) DEFAULT NULL,
  `ubicacion` varchar(64) DEFAULT NULL,
  `fecha_descarga` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observaciones` varchar(512) DEFAULT NULL,
  `img_dir` VARCHAR(300) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;