CREATE TABLE `post` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(256) DEFAULT NULL,
  `BODY` varchar(512) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
