CREATE TABLE `analisis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zaranda` FLOAT NULL,
  `caida_zaranda` FLOAT NULL,
  `incomestible` FLOAT NULL,
  `terron` FLOAT NULL,
  `manchado` FLOAT NULL,
  `partido` FLOAT NULL,
  `helado` FLOAT NULL,
  `chuzo` FLOAT NULL,
  `marron` FLOAT NULL,
  `roido` FLOAT NULL,
  `p_de_c` FLOAT NULL,
  `contrastante` FLOAT NULL,
  `leve_A` FLOAT NULL,
  `leve_B` FLOAT NULL,
  `descorticado` FLOAT NULL,
  `cascado` FLOAT NULL,
  `arrugado` FLOAT NULL,
  `revolcado` FLOAT NULL,
  `manchado_maquina` FLOAT NULL,
  `punta_chaucha` FLOAT NULL,
  `pinto` FLOAT NULL,
  `bolita` FLOAT NULL,
  `oxidado` FLOAT NULL,
  `quebrado` FLOAT NULL,
  `brotado` FLOAT NULL,
  `venoso` FLOAT NULL,
  `decolorido` FLOAT NULL,
  `humedad` FLOAT NULL,
  `gramaje` FLOAT NULL,
  `hidratacion` FLOAT NULL,
  `fecha_realizacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
  