CREATE TABLE `AGROQUIMICO_RETIRO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORDEN_TRABAJO` VARCHAR(128) NULL,
  `CANTIDAD` INT(6) NOT NULL,
  `FECHA` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AGROQUIMICO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`));
