CREATE TABLE `FINCA_LOTE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FINCA_ID` int(11) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  `CANT_HA` int(11) DEFAULT NULL,
  `NOTA` varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
