CREATE TABLE `APLICACION_TIPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `PRECIO_HA` DOUBLE NULL,
  PRIMARY KEY (`ID`));
  
INSERT INTO `APLICACION_TIPO` (`NOMBRE`, `PRECIO_HA`) VALUES ('Terrestre', '6');
INSERT INTO `APLICACION_TIPO` (`NOMBRE`, `PRECIO_HA`) VALUES ('Aerea', '10');
