CREATE TABLE `AGROQUIMICO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FECHA_COMPRA` datetime DEFAULT CURRENT_TIMESTAMP,
  `FECHA_VENCIMIENTO` datetime DEFAULT NULL,
  `FECHA_MODIFICACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FACTURA` varchar(45) DEFAULT NULL,
  `LOTE_CODIGO` varchar(45) DEFAULT NULL,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `NOTA` varchar(512) DEFAULT NULL,
  `AGROQUIMICO_TIPO` tinyint(3) DEFAULT '1',
  `CANTIDAD` int(9) DEFAULT NULL,
  `UNIDAD_MEDIDA` tinyint(2) DEFAULT '1',
  `PRINCIPIO_ACTIVO` varchar(128) DEFAULT NULL,
  `CONCENTRACION_PA` float DEFAULT '0',
  `PRECIO` double DEFAULT '0',
  `LABORATORIO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

