CREATE TABLE `AGROQUIMICO_APLICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `APLICACION_NRO` INT NULL,
  `APPLICACION_TIPO` INT NULL,
  `ARGROQUIMICO_ID` INT NULL,
  `LOTE_ID` INT NULL,
  `CANT_HA` INT NULL,
  `DOSIS` DOUBLE NULL,
  PRIMARY KEY (`ID`));
