CREATE TABLE `AGROQUIMICO_APLICACION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APLICACION_ID` int(11) NOT NULL,
  `ARGROQUIMICO_ID` int(11) NOT NULL,
  `DOSIS` double NOT NULL,
PRIMARY KEY (`ID`));
