CREATE TABLE `AGROQUIMICO_TIPO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOMBRE_UNIQUE` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Insecticida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Herbicida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Fertilizante');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Fungicida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Acaricida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Nematicida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Rodenticida');
INSERT INTO `AGROQUIMICO_TIPO` (`NOMBRE`) VALUES ('Fitorregulador');
