ALTER TABLE `agroquimico` 
CHANGE COLUMN `CANTIDAD` `CANTIDAD` FLOAT NULL DEFAULT NULL ;

ALTER TABLE `agroquimico` 
CHANGE COLUMN `PRECIO` `PRECIO` FLOAT NULL DEFAULT '0' ;

ALTER TABLE `agroquimico_retiro` 
CHANGE COLUMN `CANTIDAD` `CANTIDAD` FLOAT NOT NULL ;

ALTER TABLE `agroquimico_aplicacion` 
CHANGE COLUMN `DOSIS` `DOSIS` FLOAT NOT NULL ;
