ALTER TABLE `AGROQUIMICO` 
CHANGE COLUMN `CANTIDAD` `CANTIDAD` FLOAT NULL DEFAULT NULL ;

ALTER TABLE `AGROQUIMICO` 
CHANGE COLUMN `PRECIO` `PRECIO` FLOAT NULL DEFAULT '0' ;

ALTER TABLE `AGROQUIMICO_RETIRO` 
CHANGE COLUMN `CANTIDAD` `CANTIDAD` FLOAT NOT NULL ;

ALTER TABLE `AGROQUIMICO_APLICACION` 
CHANGE COLUMN `DOSIS` `DOSIS` FLOAT NOT NULL ;
